# Generated by Django 6.0.2 on 2026-02-11 21:13

import django.db.models.deletion
import djgeoaddress.fields
import djproviderkit.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissiveProviderModel",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="Provider name (e.g., sendgrid)",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Provider display name", verbose_name="Display Name"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Provider description", verbose_name="Description"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        help_text="Provider priority", verbose_name="Priority"
                    ),
                ),
                (
                    "config_status_str",
                    models.CharField(
                        help_text="Config status", verbose_name="Config status"
                    ),
                ),
                (
                    "config_prefix",
                    models.CharField(
                        help_text="Config prefix", verbose_name="Config prefix"
                    ),
                ),
                (
                    "config_keys",
                    models.JSONField(
                        help_text="Config keys", verbose_name="Config keys"
                    ),
                ),
                (
                    "missing_config_keys",
                    models.JSONField(
                        help_text="Missing config keys",
                        verbose_name="Missing config keys",
                    ),
                ),
                (
                    "is_config_ready",
                    models.BooleanField(
                        help_text="Is config ready", verbose_name="Is config ready"
                    ),
                ),
                (
                    "package_status_str",
                    models.CharField(
                        help_text="Package status", verbose_name="Package status"
                    ),
                ),
                (
                    "required_packages",
                    models.JSONField(
                        help_text="Required packages", verbose_name="Required packages"
                    ),
                ),
                (
                    "missing_packages",
                    models.JSONField(
                        help_text="Missing packages", verbose_name="Missing packages"
                    ),
                ),
                (
                    "are_packages_installed",
                    models.BooleanField(
                        help_text="Are packages installed",
                        verbose_name="Are packages installed",
                    ),
                ),
                (
                    "service_status_str",
                    models.CharField(
                        help_text="Service status", verbose_name="Service status"
                    ),
                ),
                (
                    "missing_services",
                    models.JSONField(
                        help_text="Missing services", verbose_name="Missing services"
                    ),
                ),
                (
                    "services",
                    models.JSONField(help_text="Services", verbose_name="Services"),
                ),
                (
                    "are_services_implemented",
                    models.BooleanField(
                        help_text="Are services implemented",
                        verbose_name="Are services implemented",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
                "ordering": ["-priority", "name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MissiveWebhook",
            fields=[
                (
                    "provider",
                    djproviderkit.fields.ProviderField(
                        blank=True,
                        help_text="Provider used to send this missive",
                        max_length=100,
                        null=True,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "webhook_id",
                    models.CharField(
                        help_text="Webhook ID",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Webhook ID",
                    ),
                ),
                ("id", models.CharField(help_text="ID", verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("postal", "Postal mail"),
                            ("postal_registered", "Registered postal mail"),
                            (
                                "postal_signature",
                                "Registered postal mail with signature",
                            ),
                            ("lre", "Electronic registered letter"),
                            ("lre_qualified", "Qualified electronic registered letter"),
                            ("ere", "Electronic registered email (ERE)"),
                            ("email", "Email"),
                            ("email_marketing", "Marketing email"),
                            ("sms", "SMS"),
                            ("rcs", "RCS (Rich SMS)"),
                            ("voice_call", "Automated voice call"),
                            ("notification", "In-app notification"),
                            ("push_notification", "Mobile push notification"),
                            (
                                "branded",
                                "Branded App messaging (WhatsApp, Slack, etc.)",
                            ),
                        ],
                        help_text="Type",
                        verbose_name="Type",
                    ),
                ),
                ("url", models.CharField(help_text="URL", verbose_name="URL")),
                (
                    "description",
                    models.CharField(
                        help_text="Description", verbose_name="Description"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        help_text="Created At", verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        help_text="Updated At", verbose_name="Updated At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Missive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    djproviderkit.fields.ProviderField(
                        blank=True,
                        help_text="Provider used to send this missive",
                        max_length=100,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "missive_type",
                    models.CharField(
                        choices=[
                            ("postal", "Postal mail"),
                            ("postal_registered", "Registered postal mail"),
                            (
                                "postal_signature",
                                "Registered postal mail with signature",
                            ),
                            ("lre", "Electronic registered letter"),
                            ("lre_qualified", "Qualified electronic registered letter"),
                            ("ere", "Electronic registered email (ERE)"),
                            ("email", "Email"),
                            ("email_marketing", "Marketing email"),
                            ("sms", "SMS"),
                            ("rcs", "RCS (Rich SMS)"),
                            ("voice_call", "Automated voice call"),
                            ("notification", "In-app notification"),
                            ("push_notification", "Mobile push notification"),
                            (
                                "branded",
                                "Branded App messaging (WhatsApp, Slack, etc.)",
                            ),
                        ],
                        help_text="Type of missive (email, SMS, postal, etc.)",
                        max_length=50,
                        verbose_name="Missive Type",
                    ),
                ),
                (
                    "acknowledgement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("basic_delivery", "Basic delivery"),
                            (
                                "acknowledgement_of_receipt",
                                "Acknowledgement of receipt",
                            ),
                            (
                                "authenticated_acknowledgement",
                                "Authenticated acknowledgement",
                            ),
                            ("signed_acknowledgement", "Signed acknowledgement"),
                            (
                                "qualified_acknowledgement",
                                "Qualified / legally binding acknowledgement",
                            ),
                        ],
                        help_text="Desired acknowledgement level for delivery proof",
                        max_length=50,
                        null=True,
                        verbose_name="Acknowledgement Level",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                        ],
                        default="draft",
                        help_text="Current status of the missive",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        help_text="Priority level",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        blank=True,
                        help_text="Sender's full name or company name",
                        max_length=255,
                        verbose_name="Sender Name",
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        blank=True,
                        help_text="Sender's email address",
                        max_length=254,
                        null=True,
                        verbose_name="Sender Email",
                    ),
                ),
                (
                    "sender_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Sender's phone number",
                        max_length=20,
                        null=True,
                        region=None,
                        verbose_name="Sender Phone",
                    ),
                ),
                (
                    "sender_address",
                    djgeoaddress.fields.GeoaddressField(
                        blank=True,
                        help_text="Sender's address",
                        null=True,
                        verbose_name="Sender Address",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's full name or company name",
                        max_length=255,
                        verbose_name="Recipient Name",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True,
                        help_text="Recipient's email address",
                        max_length=254,
                        null=True,
                        verbose_name="Recipient Email",
                    ),
                ),
                (
                    "recipient_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Recipient's phone number",
                        max_length=20,
                        null=True,
                        region=None,
                        verbose_name="Recipient Phone",
                    ),
                ),
                (
                    "recipient_address",
                    djgeoaddress.fields.GeoaddressField(
                        blank=True,
                        help_text="Recipient's address",
                        null=True,
                        verbose_name="Recipient Address",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject line (for email, SMS, etc.)",
                        max_length=500,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Message body/content",
                        verbose_name="Body",
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        blank=True,
                        help_text="Plain text version of the message",
                        verbose_name="Body Text",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="External identifier from the provider",
                        max_length=255,
                        null=True,
                        verbose_name="External ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the missive was sent",
                        null=True,
                        verbose_name="Sent At",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the missive was delivered",
                        null=True,
                        verbose_name="Delivered At",
                    ),
                ),
                (
                    "is_billed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the missive has been billed",
                        verbose_name="Billed",
                    ),
                ),
                (
                    "billing_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount billed for the missive",
                        max_digits=10,
                        null=True,
                        verbose_name="Billing Amount",
                    ),
                ),
                (
                    "estimate_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated amount for the missive",
                        max_digits=10,
                        null=True,
                        verbose_name="Estimate Amount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Missive",
                "verbose_name_plural": "Missives",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MissiveAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_object_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of the object to which this file is attached",
                        null=True,
                        verbose_name="Object ID",
                    ),
                ),
                (
                    "file_method_access",
                    models.CharField(
                        blank=True,
                        help_text="Method to access the file",
                        max_length=255,
                        verbose_name="File Method Access",
                    ),
                ),
                (
                    "files_object_arguments",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arguments to pass to the file method (as dict for **kwargs)",
                        verbose_name="File Object Arguments",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Leave blank if the file is hosted externally",
                        null=True,
                        upload_to="missive/attachments/%Y/%m/%d/",
                        verbose_name="Local File",
                    ),
                ),
                (
                    "file_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata of the file",
                        verbose_name="File Metadata",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order", verbose_name="Order"
                    ),
                ),
                (
                    "multiple_files",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this is a related function that returns multiple files",
                        verbose_name="Multiple Files",
                    ),
                ),
                (
                    "file_content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of model to which this file is attached",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Object Type",
                    ),
                ),
                (
                    "missive",
                    models.ForeignKey(
                        blank=True,
                        help_text="Missive to which this file is attached",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="djpymissive.missive",
                        verbose_name="Missive",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MissiveEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("opened", "Opened"),
                            ("click", "Clicked"),
                            ("clicked", "Clicked"),
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("prepare", "Prepare"),
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("queued", "Queued"),
                            ("request", "Request"),
                            ("deferred", "Deferred"),
                            ("scheduled", "Scheduled"),
                            ("unknown_type", "Unknown type"),
                            ("attempted_delivery", "Attempted delivery"),
                            ("mailed", "Mailed"),
                            ("printed", "Printed"),
                            ("accepted", "Accepted"),
                            ("dispatched", "Dispatched"),
                            ("shipped", "Shipped"),
                            ("in_transit", "In transit"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("bounced", "Bounced"),
                            ("hard_bounce", "Hard bounce"),
                            ("soft_bounce", "Soft bounce"),
                            ("hardBounce", "Hard bounce"),
                            ("softBounce", "Soft bounce"),
                            ("dropped", "Dropped"),
                            ("spam", "Spam"),
                            ("blocked", "Blocked"),
                            ("invalid", "Invalid"),
                            ("mailbox_not_found", "Mailbox not found"),
                            ("blocklisted", "Blocklisted"),
                            ("blocklist_created", "Blocklist created"),
                            ("rejected", "Rejected"),
                            ("undelivered", "Undelivered"),
                            ("undeliverable", "Undeliverable"),
                            ("expired", "Expired"),
                            ("carrier_rejected", "Carrier rejected"),
                            ("return_to_sender", "Return to sender"),
                            ("refused", "Refused"),
                            ("lost", "Lost"),
                            ("damaged", "Damaged"),
                            ("out_for_delivery", "Out for delivery"),
                        ],
                        help_text="Event type (sent, delivered, read, failed, etc.)",
                        max_length=50,
                        null=True,
                        verbose_name="Event",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description or details about this event",
                        verbose_name="Description",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "trace",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw trace data (webhook payload, API response, etc.)",
                        verbose_name="Trace",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this event occurred",
                        verbose_name="Occurred At",
                    ),
                ),
                (
                    "missive",
                    models.ForeignKey(
                        help_text="Missive associated with this event",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_missiveevent",
                        to="djpymissive.missive",
                        verbose_name="Missive",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="MissiveRelatedObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="ID of the related object", verbose_name="Object ID"
                    ),
                ),
                (
                    "object_str",
                    models.CharField(
                        blank=True,
                        help_text="String representation of the related object (saved for reference if object is deleted)",
                        max_length=500,
                        verbose_name="Object String Representation",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type of the related object",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "missive",
                    models.ForeignKey(
                        help_text="Missive to which this object is related",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_missiverelatedobject",
                        to="djpymissive.missive",
                        verbose_name="Missive",
                    ),
                ),
            ],
            options={
                "verbose_name": "Related Object",
                "verbose_name_plural": "Related Objects",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["missive", "-created_at"],
                        name="djpymissive_missive_4e8124_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="djpymissive_content_c2ece8_idx",
                    ),
                ],
            },
        ),
    ]
