# Generated by Django 6.0.2 on 2026-02-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissiveProviderModel',
            fields=[
                ('name', models.CharField(help_text='Provider name (e.g., sendgrid)', max_length=255, primary_key=True, serialize=False, verbose_name='Name')),
                ('display_name', models.CharField(help_text='Provider display name', verbose_name='Display Name')),
                ('description', models.CharField(help_text='Provider description', verbose_name='Description')),
                ('priority', models.IntegerField(help_text='Provider priority', verbose_name='Priority')),
                ('config_status_str', models.CharField(help_text='Config status', verbose_name='Config status')),
                ('config_prefix', models.CharField(help_text='Config prefix', verbose_name='Config prefix')),
                ('config_keys', models.JSONField(help_text='Config keys', verbose_name='Config keys')),
                ('missing_config_keys', models.JSONField(help_text='Missing config keys', verbose_name='Missing config keys')),
                ('is_config_ready', models.BooleanField(help_text='Is config ready', verbose_name='Is config ready')),
                ('package_status_str', models.CharField(help_text='Package status', verbose_name='Package status')),
                ('required_packages', models.JSONField(help_text='Required packages', verbose_name='Required packages')),
                ('missing_packages', models.JSONField(help_text='Missing packages', verbose_name='Missing packages')),
                ('are_packages_installed', models.BooleanField(help_text='Are packages installed', verbose_name='Are packages installed')),
                ('service_status_str', models.CharField(help_text='Service status', verbose_name='Service status')),
                ('missing_services', models.JSONField(help_text='Missing services', verbose_name='Missing services')),
                ('services', models.JSONField(help_text='Services', verbose_name='Services')),
                ('are_services_implemented', models.BooleanField(help_text='Are services implemented', verbose_name='Are services implemented')),
            ],
            options={
                'verbose_name': 'Missive Provider',
                'verbose_name_plural': 'Missive Providers',
                'ordering': ['-priority', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Missive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, help_text="Sender's full name or company name", max_length=255, verbose_name='Sender Name')),
                ('sender_email', models.EmailField(blank=True, help_text="Sender's email address", max_length=254, null=True, verbose_name='Sender Email')),
                ('sender_phone', models.CharField(blank=True, help_text="Sender's phone number", max_length=20, null=True, verbose_name='Sender Phone')),
                ('recipient_name', models.CharField(blank=True, help_text="Recipient's full name or company name", max_length=255, verbose_name='Recipient Name')),
                ('recipient_email', models.EmailField(blank=True, help_text="Recipient's email address", max_length=254, null=True, verbose_name='Recipient Email')),
                ('recipient_phone', models.CharField(blank=True, help_text="Recipient's phone number", max_length=20, null=True, verbose_name='Recipient Phone')),
                ('missive_type', models.CharField(choices=[('POSTAL', 'Postal mail'), ('POSTAL_REGISTERED', 'Registered postal mail'), ('POSTAL_SIGNATURE', 'Registered postal mail with signature'), ('LRE', 'Electronic registered letter'), ('LRE_QUALIFIED', 'Qualified electronic registered letter'), ('ERE', 'Electronic registered email (ERE)'), ('EMAIL', 'Email'), ('EMAIL_MARKETING', 'Marketing email'), ('SMS', 'SMS'), ('RCS', 'RCS (Rich SMS)'), ('VOICE_CALL', 'Automated voice call'), ('NOTIFICATION', 'In-app notification'), ('PUSH_NOTIFICATION', 'Mobile push notification'), ('BRANDED', 'App messaging')], help_text='Type of missive (email, SMS, postal, etc.)', max_length=50, verbose_name='Missive Type')),
                ('subject', models.CharField(blank=True, help_text='Subject line (for email, SMS, etc.)', max_length=500, verbose_name='Subject')),
                ('body', models.TextField(blank=True, help_text='Message body/content', verbose_name='Body')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current status of the missive', max_length=50, verbose_name='Status')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', help_text='Priority level', max_length=20, verbose_name='Priority')),
                ('provider_name', models.CharField(blank=True, help_text='Name of the provider used to send this missive', max_length=255, verbose_name='Provider Name')),
                ('external_id', models.CharField(blank=True, help_text='External identifier from the provider', max_length=255, null=True, verbose_name='External ID')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON', verbose_name='Metadata')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object', null=True, verbose_name='Object ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the missive was sent', null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the missive was delivered', null=True, verbose_name='Delivered At')),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of the related object', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'Missive',
                'verbose_name_plural': 'Missives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissiveAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the object to which this file is attached', null=True, verbose_name='Object ID')),
                ('file_method_access', models.CharField(blank=True, help_text='Method to access the file', max_length=255, verbose_name='File Method Access')),
                ('file', models.FileField(blank=True, help_text='Leave blank if the file is hosted externally', null=True, upload_to='missive/attachments/%Y/%m/%d/', verbose_name='Local File')),
                ('file_metadata', models.JSONField(blank=True, default=dict, help_text='Metadata of the file', verbose_name='File Metadata')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order', verbose_name='Order')),
                ('file_content_type', models.ForeignKey(blank=True, help_text='Type of model to which this file is attached', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Object Type')),
                ('missive', models.ForeignKey(blank=True, help_text='Missive to which this file is attached', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='djpymissive.missive', verbose_name='Missive')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MissiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Type of event (sent, delivered, read, failed, etc.)', max_length=100, verbose_name='Event Type')),
                ('status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], help_text='Status associated with this event', max_length=50, null=True, verbose_name='Status')),
                ('description', models.TextField(blank=True, help_text='Description or details about this event', verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON', verbose_name='Metadata')),
                ('trace', models.JSONField(blank=True, default=dict, help_text='Raw trace data (webhook payload, API response, etc.)', verbose_name='Trace')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, help_text='When this event occurred', verbose_name='Occurred At')),
                ('missive', models.ForeignKey(help_text='Missive associated with this event', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='djpymissive.missive', verbose_name='Missive')),
            ],
            options={
                'verbose_name': 'Missive Event',
                'verbose_name_plural': 'Missive Events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='missive',
            index=models.Index(fields=['missive_type', 'status'], name='djpymissive_missive_2caa4a_idx'),
        ),
        migrations.AddIndex(
            model_name='missive',
            index=models.Index(fields=['status', 'created_at'], name='djpymissive_status_4ebfb9_idx'),
        ),
        migrations.AddIndex(
            model_name='missive',
            index=models.Index(fields=['provider_name', 'external_id'], name='djpymissive_provide_ad295e_idx'),
        ),
        migrations.AddIndex(
            model_name='missive',
            index=models.Index(fields=['content_type', 'object_id'], name='djpymissive_content_197595_idx'),
        ),
    ]
