# Generated by Django 6.0.2 on 2026-02-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpymissive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missive',
            name='brand_name',
            field=models.CharField(blank=True, help_text='Brand name used to send this missive', max_length=50, null=True, verbose_name='Brand Name'),
        ),
        migrations.AddField(
            model_name='missiverecipient',
            name='notification_id',
            field=models.CharField(blank=True, help_text='Notification ID', max_length=255, null=True, verbose_name='Notification ID'),
        ),
    ]
