# Generated by Django 6.0.2 on 2026-02-06 15:41

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djpymissive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missive',
            name='recipient_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Recipient's phone number", max_length=20, null=True, region=None, verbose_name='Recipient Phone'),
        ),
        migrations.AlterField(
            model_name='missive',
            name='sender_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Sender's phone number", max_length=20, null=True, region=None, verbose_name='Sender Phone'),
        ),
    ]
