# Generated by Django 6.0.2 on 2026-02-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djpymissive", "0002_missiverecipientaddress_missiverecipientemail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="missiverecipient",
            name="recipient_model",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("address", "Address"),
                    ("notification", "Notification"),
                ],
                default="email",
                help_text="Model of recipient",
                max_length=255,
                verbose_name="Recipient Model",
            ),
        ),
    ]
