# Generated by Django 6.0.2 on 2026-02-06 15:57

import djproviderkit.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('djpymissive', '0002_alter_missive_recipient_phone_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='missive',
            name='djpymissive_provide_ad295e_idx',
        ),
        migrations.AddField(
            model_name='missive',
            name='provider',
            field=djproviderkit.fields.ProviderField(blank=True, help_text='Provider used to send this missive', max_length=255, verbose_name='Provider'),
        ),
        migrations.AddIndex(
            model_name='missive',
            index=models.Index(fields=['provider', 'external_id'], name='djpymissive_provide_5321f9_idx'),
        ),
        migrations.RemoveField(
            model_name='missive',
            name='provider_name',
        ),
    ]
