# Generated by Django 6.0.2 on 2026-02-14 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpymissive', '0002_missive_brand_name_missiverecipient_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missivecampaign',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
