# Generated by Django 6.0.2 on 2026-02-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djpymissive", "0003_missiverecipient_recipient_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissiveServiceModel",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="Service name",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Name",
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        help_text="Service fields", verbose_name="Service fields"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Service description",
                        verbose_name="Service description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Service",
                "verbose_name_plural": "Provider Services",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="missive",
            name="webhook_url",
            field=models.URLField(
                blank=True,
                help_text="Webhook URL for the missive",
                max_length=255,
                null=True,
                verbose_name="Webhook URL",
            ),
        ),
    ]
