# Generated by Django 6.0.2 on 2026-02-06 16:22

import djproviderkit.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpymissive', '0003_remove_missive_djpymissive_provide_ad295e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missive',
            name='acknowledgement',
            field=models.CharField(blank=True, choices=[('none', 'No acknowledgement')], help_text='Desired acknowledgement level for delivery proof', max_length=50, null=True, verbose_name='Acknowledgement Level'),
        ),
        migrations.AlterField(
            model_name='missive',
            name='provider',
            field=djproviderkit.fields.ProviderField(blank=True, help_text='Provider used to send this missive', max_length=100, verbose_name='Provider'),
        ),
    ]
