# Generated by Django 6.0.2 on 2026-02-06 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('djpymissive', '0004_missive_acknowledgement_alter_missive_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissiveRelatedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the related object', verbose_name='Object ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Missive Related Object',
                'verbose_name_plural': 'Missive Related Objects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='missive',
            name='djpymissive_content_197595_idx',
        ),
        migrations.AlterField(
            model_name='missive',
            name='acknowledgement',
            field=models.CharField(blank=True, choices=[('basic_delivery', 'Basic delivery'), ('acknowledgement_of_receipt', 'Acknowledgement of receipt'), ('authenticated_acknowledgement', 'Authenticated acknowledgement'), ('signed_acknowledgement', 'Signed acknowledgement'), ('qualified_acknowledgement', 'Qualified / legally binding acknowledgement')], help_text='Desired acknowledgement level for delivery proof', max_length=50, null=True, verbose_name='Acknowledgement Level'),
        ),
        migrations.AlterField(
            model_name='missive',
            name='missive_type',
            field=models.CharField(choices=[('POSTAL', 'Postal mail'), ('POSTAL_REGISTERED', 'Registered postal mail'), ('POSTAL_SIGNATURE', 'Registered postal mail with signature'), ('LRE', 'Electronic registered letter'), ('LRE_QUALIFIED', 'Qualified electronic registered letter'), ('ERE', 'Electronic registered email (ERE)'), ('EMAIL', 'Email'), ('EMAIL_MARKETING', 'Marketing email'), ('SMS', 'SMS'), ('RCS', 'RCS (Rich SMS)'), ('VOICE_CALL', 'Automated voice call'), ('NOTIFICATION', 'In-app notification'), ('PUSH_NOTIFICATION', 'Mobile push notification'), ('BRANDED', 'Branded App messaging (WhatsApp, Slack, etc.)')], help_text='Type of missive (email, SMS, postal, etc.)', max_length=50, verbose_name='Missive Type'),
        ),
        migrations.AddField(
            model_name='missiverelatedobject',
            name='content_type',
            field=models.ForeignKey(help_text='Type of the related object', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='missiverelatedobject',
            name='missive',
            field=models.ForeignKey(help_text='Missive to which this object is related', on_delete=django.db.models.deletion.CASCADE, related_name='related_objects', to='djpymissive.missive', verbose_name='Missive'),
        ),
        migrations.RemoveField(
            model_name='missive',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='missive',
            name='object_id',
        ),
        migrations.AddIndex(
            model_name='missiverelatedobject',
            index=models.Index(fields=['missive', '-created_at'], name='djpymissive_missive_4e8124_idx'),
        ),
        migrations.AddIndex(
            model_name='missiverelatedobject',
            index=models.Index(fields=['content_type', 'object_id'], name='djpymissive_content_c2ece8_idx'),
        ),
    ]
