# Generated by Django 5.2.8 on 2025-11-09 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du provider"),
                ),
                (
                    "missive_type",
                    models.CharField(max_length=50, verbose_name="Type de missive"),
                ),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="MissiveTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom du template pour le retrouver facilement",
                        max_length=255,
                        verbose_name="Nom du template",
                    ),
                ),
                (
                    "missive_type",
                    models.CharField(
                        choices=[
                            ("POSTAL", "Courrier postal"),
                            ("LRE", "Lettre recommandée électronique"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("RCS", "RCS (SMS enrichi)"),
                            ("WHATSAPP", "WhatsApp"),
                            ("TELEGRAM", "Telegram"),
                            ("SIGNAL", "Signal"),
                            ("MESSENGER", "Facebook Messenger"),
                            ("VOICE_CALL", "Appel vocal automatisé"),
                            ("NOTIFICATION", "Notification in-app"),
                            ("PUSH_NOTIFICATION", "Notification push mobile"),
                            ("SLACK", "Slack"),
                            ("TEAMS", "Microsoft Teams"),
                        ],
                        help_text="Type de missive pour lequel ce template sera utilisé",
                        max_length=20,
                        verbose_name="Type de missive",
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        help_text="Peut contenir des variables : {{variable}}",
                        max_length=255,
                        verbose_name="Template du sujet",
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        help_text="Peut contenir des variables : {{variable}}",
                        verbose_name="Template du corps",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Désactiver pour masquer ce template sans le supprimer",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date de création automatique du template",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date de dernière modification automatique",
                        verbose_name="Date de modification",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Utilisateur qui a créé ce template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de missive",
                "verbose_name_plural": "Templates de missives",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID de l'objet lié",
                        null=True,
                        verbose_name="ID de l'objet",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Particulier"),
                            ("COMPANY", "Entreprise"),
                            ("ADMINISTRATION", "Administration"),
                        ],
                        default="INDIVIDUAL",
                        help_text="Particulier, Entreprise ou Administration",
                        max_length=20,
                        verbose_name="Type de destinataire",
                    ),
                ),
                (
                    "civility",
                    models.CharField(
                        blank=True,
                        help_text="M., Mme, Dr, etc.",
                        max_length=10,
                        verbose_name="Civilité",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        help_text="Nom complet (personne) ou dénomination (entreprise/administration)",
                        max_length=255,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Adresse email du destinataire",
                        max_length=254,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de téléphone mobile au format international (ex: +33 6 12 34 56 78)",
                        max_length=20,
                        null=True,
                        verbose_name="Téléphone mobile",
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True,
                        help_text="Numéro et nom de rue",
                        max_length=255,
                        verbose_name="Adresse ligne 1",
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        help_text="Bâtiment, appartement, étage (optionnel)",
                        max_length=255,
                        verbose_name="Adresse ligne 2",
                    ),
                ),
                (
                    "address_line3",
                    models.CharField(
                        blank=True,
                        help_text="Complément d'adresse (optionnel)",
                        max_length=255,
                        verbose_name="Adresse ligne 3",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Code postal",
                        max_length=20,
                        verbose_name="Code postal",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Ville",
                        max_length=100,
                        verbose_name="Ville",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="Région, département ou état",
                        max_length=100,
                        verbose_name="État/Région",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="FR",
                        help_text="Code pays ISO (FR, BE, CH, etc.)",
                        max_length=2,
                        verbose_name="Pays (code ISO)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes internes sur ce destinataire",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Désactiver pour masquer ce destinataire sans le supprimer",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "can_be_sender",
                    models.BooleanField(
                        default=False,
                        help_text="Cocher si ce destinataire peut être utilisé comme expéditeur de missives",
                        verbose_name="Utilisable comme expéditeur",
                    ),
                ),
                (
                    "is_default_sender",
                    models.BooleanField(
                        default=False,
                        help_text="Un seul expéditeur par défaut possible dans le système",
                        verbose_name="Expéditeur par défaut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date de création automatique",
                        verbose_name="Créé le",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date de dernière modification automatique",
                        verbose_name="Modifié le",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type d'objet lié (Customer, Contact, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Type d'objet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destinataire",
                "verbose_name_plural": "Destinataires",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Missive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID de l'objet source",
                        null=True,
                        verbose_name="ID de l'objet source",
                    ),
                ),
                (
                    "missive_type",
                    models.CharField(
                        choices=[
                            ("POSTAL", "Courrier postal"),
                            ("LRE", "Lettre recommandée électronique"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("RCS", "RCS (SMS enrichi)"),
                            ("WHATSAPP", "WhatsApp"),
                            ("TELEGRAM", "Telegram"),
                            ("SIGNAL", "Signal"),
                            ("MESSENGER", "Facebook Messenger"),
                            ("VOICE_CALL", "Appel vocal automatisé"),
                            ("NOTIFICATION", "Notification in-app"),
                            ("PUSH_NOTIFICATION", "Notification push mobile"),
                            ("SLACK", "Slack"),
                            ("TEAMS", "Microsoft Teams"),
                        ],
                        help_text="Email, SMS, WhatsApp, Courrier postal ou Notification",
                        max_length=20,
                        verbose_name="Type de missive",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Basse"),
                            ("NORMAL", "Normale"),
                            ("HIGH", "Haute"),
                            ("URGENT", "Urgente"),
                        ],
                        default="NORMAL",
                        help_text="Basse, Normale, Haute ou Urgente",
                        max_length=10,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Titre ou objet de la missive",
                        max_length=255,
                        verbose_name="Sujet",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Corps du message (HTML pour emails, texte pour SMS/WhatsApp)",
                        verbose_name="Contenu HTML",
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        blank=True,
                        help_text="Version texte brut du message (fallback pour emails, obligatoire pour SMS)",
                        verbose_name="Contenu texte brut",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Variables JSON pour le rendu du template (ex: {'nom': 'Dupont', 'montant': 150})",
                        verbose_name="Variables de contexte",
                    ),
                ),
                (
                    "is_registered",
                    models.BooleanField(
                        default=False,
                        help_text="Email ou courrier recommandé avec accusé de réception",
                        verbose_name="Recommandé",
                    ),
                ),
                (
                    "requires_signature",
                    models.BooleanField(
                        default=False,
                        help_text="Pour courrier recommandé avec signature",
                        verbose_name="Signature requise",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En cours de traitement"),
                            ("SENT", "Envoyé"),
                            ("DELIVERED", "Délivré"),
                            ("READ", "Lu"),
                            ("FAILED", "Échec"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="DRAFT",
                        help_text="Brouillon, En attente, Envoyé, Délivré, Lu, Échec ou Annulé",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date de création automatique de la missive",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date de dernière modification automatique",
                        verbose_name="Date de modification",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Laisser vide pour envoi immédiat",
                        null=True,
                        verbose_name="Date d'envoi programmée",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date et heure d'envoi effective de la missive",
                        null=True,
                        verbose_name="Date d'envoi",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date et heure de réception confirmée par le destinataire",
                        null=True,
                        verbose_name="Date de réception",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date et heure d'ouverture par le destinataire",
                        null=True,
                        verbose_name="Date de lecture",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Référence de tracking du provider (LaPoste, SendGrid, etc.)",
                        max_length=255,
                        null=True,
                        verbose_name="Référence externe",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Message d'erreur en cas d'échec d'envoi",
                        null=True,
                        verbose_name="Message d'erreur",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données additionnelles au format JSON",
                        verbose_name="Métadonnées",
                    ),
                ),
                (
                    "attachments_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre total de pièces jointes associées",
                        verbose_name="Nombre de pièces jointes",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Coût d'envoi en euros",
                        max_digits=10,
                        null=True,
                        verbose_name="Coût",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type du modèle qui génère cette missive (Order, Participant, Invoice, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Type d'objet source",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optionnel si 'recipient' est fourni",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_missives",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire (utilisateur)",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Destinataire de cette missive (utilise le modèle Recipient)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_missives",
                        to="missive.recipient",
                        verbose_name="Destinataire",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="Expéditeur de cette missive (utilise le modèle Recipient)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_missives",
                        to="missive.recipient",
                        verbose_name="Expéditeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Missive",
                "verbose_name_plural": "Missives",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MissiveAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID de l'objet auquel ce fichier est attaché",
                        null=True,
                        verbose_name="ID de l'objet",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Laisser vide si le fichier est hébergé en externe",
                        null=True,
                        upload_to="missive/attachments/%Y/%m/%d/",
                        verbose_name="Fichier local",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="URL du fichier hébergé en externe (S3, Google Drive, etc.)",
                        max_length=500,
                        null=True,
                        verbose_name="URL externe",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Nom du fichier avec extension",
                        max_length=255,
                        verbose_name="Nom du fichier",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description ou notes sur cette pièce jointe",
                        verbose_name="Description",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Taille du fichier en octets",
                        null=True,
                        verbose_name="Taille (bytes)",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        help_text="Type MIME du fichier (application/pdf, image/png, etc.)",
                        max_length=100,
                        verbose_name="Type MIME",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre d'affichage (automatique si non fourni)",
                        verbose_name="Ordre",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date d'ajout automatique de la pièce jointe",
                        verbose_name="Date d'ajout",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type du modèle auquel ce fichier est attaché (Order, Invoice, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Type d'objet",
                    ),
                ),
                (
                    "missive",
                    models.ForeignKey(
                        blank=True,
                        help_text="Missive à laquelle ce fichier est attaché",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="missive.missive",
                        verbose_name="Missive",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce jointe",
                "verbose_name_plural": "Pièces jointes",
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="missive_mis_content_4ff039_idx",
                    ),
                    models.Index(
                        fields=["missive", "order"],
                        name="missive_mis_missive_b59af0_idx",
                    ),
                    models.Index(
                        fields=["missive", "created_at"],
                        name="missive_mis_missive_8f1c69_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MissiveEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Ex: created, sent, delivered, opened, clicked, bounced, etc.",
                        max_length=50,
                        verbose_name="Type d'événement",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Provider qui a généré cet événement (sendgrid, twilio, laposte, etc.)",
                        max_length=50,
                        null=True,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En cours de traitement"),
                            ("SENT", "Envoyé"),
                            ("DELIVERED", "Délivré"),
                            ("READ", "Lu"),
                            ("FAILED", "Échec"),
                            ("CANCELLED", "Annulé"),
                        ],
                        help_text="Statut de la missive suite à cet événement",
                        max_length=20,
                        null=True,
                        verbose_name="Statut associé",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée de l'événement",
                        verbose_name="Description",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données additionnelles (IP, user agent, etc.)",
                        verbose_name="Métadonnées",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de l'événement",
                        verbose_name="Date de l'événement",
                    ),
                ),
                (
                    "missive",
                    models.ForeignKey(
                        help_text="Missive associée à cet événement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="missive.missive",
                        verbose_name="Missive",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["missive", "-created_at"],
                        name="missive_mis_missive_cac075_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="missive_mis_event_t_398098_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(fields=["name"], name="missive_rec_name_18f932_idx"),
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(fields=["email"], name="missive_rec_email_17df67_idx"),
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(fields=["mobile"], name="missive_rec_mobile_cf9247_idx"),
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="missive_rec_content_5122b4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipient",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("email__isnull", False), models.Q(("email", ""), _negated=True)
                ),
                fields=("email",),
                name="unique_email",
                violation_error_message="Un destinataire avec cet email existe déjà",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipient",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("mobile__isnull", False), models.Q(("mobile", ""), _negated=True)
                ),
                fields=("mobile",),
                name="unique_mobile",
                violation_error_message="Un destinataire avec ce mobile existe déjà",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipient",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("address_line1__isnull", False),
                    models.Q(("address_line1", ""), _negated=True),
                ),
                fields=("name", "address_line1", "postal_code", "city"),
                name="unique_postal_address",
                violation_error_message="Un destinataire avec cette adresse existe déjà",
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["-created_at"], name="missive_mis_created_96fcd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["sender", "-created_at"], name="missive_mis_sender__a65902_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["recipient_user", "-created_at"],
                name="missive_mis_recipie_7403a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["status", "-created_at"], name="missive_mis_status_533fe5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["missive_type", "status"], name="missive_mis_missive_29cd10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["external_id"], name="missive_mis_externa_9aa8a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["scheduled_at"], name="missive_mis_schedul_6cdc69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="missive_mis_content_3bbb20_idx",
            ),
        ),
    ]
