# Generated by Django 5.2.8 on 2025-11-25 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Provider Name"),
                ),
                (
                    "missive_type",
                    models.CharField(max_length=50, verbose_name="Missive Type"),
                ),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
                "ordering": ["name"],
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Missive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        blank=True,
                        help_text="Sender's full name or company name",
                        max_length=255,
                        verbose_name="Sender Name",
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        blank=True,
                        help_text="Sender's email address",
                        max_length=254,
                        null=True,
                        verbose_name="Sender Email",
                    ),
                ),
                (
                    "sender_phone",
                    models.CharField(
                        blank=True,
                        help_text="Sender's phone number in international format (e.g., +33 6 12 34 56 78)",
                        max_length=20,
                        null=True,
                        verbose_name="Sender Phone",
                    ),
                ),
                (
                    "sender_address_line1",
                    models.CharField(
                        blank=True,
                        help_text="Street number and name",
                        max_length=255,
                        verbose_name="Sender Address Line 1",
                    ),
                ),
                (
                    "sender_address_line2",
                    models.CharField(
                        blank=True,
                        help_text="Building, apartment, floor (optional)",
                        max_length=255,
                        verbose_name="Sender Address Line 2",
                    ),
                ),
                (
                    "sender_address_line3",
                    models.CharField(
                        blank=True,
                        help_text="Additional address info (optional)",
                        max_length=255,
                        verbose_name="Sender Address Line 3",
                    ),
                ),
                (
                    "sender_postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Postal code",
                        max_length=20,
                        verbose_name="Sender Postal Code",
                    ),
                ),
                (
                    "sender_city",
                    models.CharField(
                        blank=True,
                        help_text="City",
                        max_length=100,
                        verbose_name="Sender City",
                    ),
                ),
                (
                    "sender_state",
                    models.CharField(
                        blank=True,
                        help_text="Region, department or state",
                        max_length=100,
                        verbose_name="Sender State/Region",
                    ),
                ),
                (
                    "sender_country",
                    models.CharField(
                        blank=True,
                        default="FR",
                        help_text="ISO country code (FR, BE, CH, etc.)",
                        max_length=2,
                        verbose_name="Sender Country (ISO code)",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's full name or company name",
                        max_length=255,
                        verbose_name="Recipient Name",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True,
                        help_text="Recipient's email address",
                        max_length=254,
                        null=True,
                        verbose_name="Recipient Email",
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's phone number in international format (e.g., +33 6 12 34 56 78)",
                        max_length=20,
                        null=True,
                        verbose_name="Recipient Phone",
                    ),
                ),
                (
                    "recipient_address_line1",
                    models.CharField(
                        blank=True,
                        help_text="Street number and name",
                        max_length=255,
                        verbose_name="Recipient Address Line 1",
                    ),
                ),
                (
                    "recipient_address_line2",
                    models.CharField(
                        blank=True,
                        help_text="Building, apartment, floor (optional)",
                        max_length=255,
                        verbose_name="Recipient Address Line 2",
                    ),
                ),
                (
                    "recipient_address_line3",
                    models.CharField(
                        blank=True,
                        help_text="Additional address info (optional)",
                        max_length=255,
                        verbose_name="Recipient Address Line 3",
                    ),
                ),
                (
                    "recipient_postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Postal code",
                        max_length=20,
                        verbose_name="Recipient Postal Code",
                    ),
                ),
                (
                    "recipient_city",
                    models.CharField(
                        blank=True,
                        help_text="City",
                        max_length=100,
                        verbose_name="Recipient City",
                    ),
                ),
                (
                    "recipient_state",
                    models.CharField(
                        blank=True,
                        help_text="Region, department or state",
                        max_length=100,
                        verbose_name="Recipient State/Region",
                    ),
                ),
                (
                    "recipient_country",
                    models.CharField(
                        blank=True,
                        default="FR",
                        help_text="ISO country code (FR, BE, CH, etc.)",
                        max_length=2,
                        verbose_name="Recipient Country (ISO code)",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Source object ID",
                        null=True,
                        verbose_name="Source Object ID",
                    ),
                ),
                (
                    "missive_type",
                    models.CharField(
                        choices=[
                            ("POSTAL", "Postal mail"),
                            ("POSTAL_REGISTERED", "Registered postal mail"),
                            (
                                "POSTAL_SIGNATURE",
                                "Registered postal mail with signature",
                            ),
                            ("LRE", "Electronic registered letter"),
                            ("LRE_QUALIFIED", "Qualified electronic registered letter"),
                            ("ERE", "Electronic registered email (ERE)"),
                            ("EMAIL", "Email"),
                            ("EMAIL_MARKETING", "Marketing email"),
                            ("SMS", "SMS"),
                            ("RCS", "RCS (Rich SMS)"),
                            ("VOICE_CALL", "Automated voice call"),
                            ("NOTIFICATION", "In-app notification"),
                            ("PUSH_NOTIFICATION", "Mobile push notification"),
                            ("BRANDED", "App messaging"),
                        ],
                        help_text="Email, SMS, WhatsApp, Postal Mail or Notification",
                        max_length=20,
                        verbose_name="Missive Type",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        help_text="Low, Normal, High or Urgent",
                        max_length=10,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Title or subject of the missive",
                        max_length=255,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Message body (HTML for emails, text for SMS/WhatsApp)",
                        verbose_name="HTML Content",
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        blank=True,
                        help_text="Plain text version of the message (fallback for emails, required for SMS)",
                        verbose_name="Plain Text Content",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON variables for template rendering (e.g., {'name': 'Smith', 'amount': 150})",
                        verbose_name="Context Variables",
                    ),
                ),
                (
                    "provider_options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific options (e.g., {'scheduled_time': 14, 'track_clicks': true, 'priority': 'high'})",
                        verbose_name="Provider Options",
                    ),
                ),
                (
                    "archiving_duration_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of days the provider keeps proofs or message records",
                        verbose_name="Archiving Duration (days)",
                    ),
                ),
                (
                    "is_registered",
                    models.BooleanField(
                        default=False,
                        help_text="Registered email or mail with acknowledgement of receipt",
                        verbose_name="Registered",
                    ),
                ),
                (
                    "requires_signature",
                    models.BooleanField(
                        default=False,
                        help_text="For registered mail with signature",
                        verbose_name="Signature Required",
                    ),
                ),
                (
                    "color_printing",
                    models.BooleanField(
                        default=False,
                        help_text="Request color printing when supported by the provider",
                        verbose_name="Color Printing",
                    ),
                ),
                (
                    "duplex_printing",
                    models.BooleanField(
                        default=True,
                        help_text="Request double-sided printing when supported by the provider",
                        verbose_name="Duplex Printing",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("READ", "Read"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        help_text="Draft, Pending, Sent, Delivered, Read, Failed or Cancelled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Automatic creation date of the missive",
                        verbose_name="Creation Date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Automatic last modification date",
                        verbose_name="Modification Date",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank for immediate sending",
                        null=True,
                        verbose_name="Scheduled Send Date",
                    ),
                ),
                (
                    "delayed_send_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When set, the missive is deferred until this exact date/time.",
                        null=True,
                        verbose_name="Delayed Send At",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Actual date and time the missive was sent",
                        null=True,
                        verbose_name="Send Date",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time of confirmed receipt by recipient",
                        null=True,
                        verbose_name="Delivery Date",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time opened by recipient",
                        null=True,
                        verbose_name="Read Date",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Provider tracking reference (LaPoste, SendGrid, etc.)",
                        max_length=255,
                        null=True,
                        verbose_name="External Reference",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message in case of sending failure",
                        null=True,
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data in JSON format",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "attachments_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of associated attachments",
                        verbose_name="Number of Attachments",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sending cost in euros",
                        max_digits=10,
                        null=True,
                        verbose_name="Cost",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of model that generates this missive (Order, Participant, Invoice, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Source Object Type",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: link to a user account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_missives",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient (user)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Missive",
                "verbose_name_plural": "Missives",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MissiveAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of the object to which this file is attached",
                        null=True,
                        verbose_name="Object ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Leave blank if the file is hosted externally",
                        null=True,
                        upload_to="missive/attachments/%Y/%m/%d/",
                        verbose_name="Local File",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of externally hosted file (S3, Google Drive, etc.)",
                        max_length=500,
                        null=True,
                        verbose_name="External URL",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Filename with extension",
                        max_length=255,
                        verbose_name="Filename",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description or notes about this attachment",
                        verbose_name="Description",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="File size in bytes",
                        null=True,
                        verbose_name="Size (bytes)",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type of the file (application/pdf, image/png, etc.)",
                        max_length=100,
                        verbose_name="MIME Type",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (automatic if not provided)",
                        verbose_name="Order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Automatic addition date of the attachment",
                        verbose_name="Date Added",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of model to which this file is attached (Order, Invoice, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Object Type",
                    ),
                ),
                (
                    "missive",
                    models.ForeignKey(
                        blank=True,
                        help_text="Missive to which this file is attached",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="missive.missive",
                        verbose_name="Missive",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="MissiveEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="E.g.: created, sent, delivered, opened, clicked, bounced, etc.",
                        max_length=50,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Provider that generated this event (sendgrid, twilio, laposte, etc.)",
                        max_length=50,
                        null=True,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("READ", "Read"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        help_text="Missive status following this event",
                        max_length=20,
                        null=True,
                        verbose_name="Associated Status",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed event description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data (IP, user agent, etc.)",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Event date and time",
                        verbose_name="Event Date",
                    ),
                ),
                (
                    "missive",
                    models.ForeignKey(
                        help_text="Missive associated with this event",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="missive.missive",
                        verbose_name="Missive",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MissiveTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name for easy retrieval",
                        max_length=255,
                        verbose_name="Template Name",
                    ),
                ),
                (
                    "missive_type",
                    models.CharField(
                        choices=[
                            ("POSTAL", "Postal mail"),
                            ("POSTAL_REGISTERED", "Registered postal mail"),
                            (
                                "POSTAL_SIGNATURE",
                                "Registered postal mail with signature",
                            ),
                            ("LRE", "Electronic registered letter"),
                            ("LRE_QUALIFIED", "Qualified electronic registered letter"),
                            ("ERE", "Electronic registered email (ERE)"),
                            ("EMAIL", "Email"),
                            ("EMAIL_MARKETING", "Marketing email"),
                            ("SMS", "SMS"),
                            ("RCS", "RCS (Rich SMS)"),
                            ("VOICE_CALL", "Automated voice call"),
                            ("NOTIFICATION", "In-app notification"),
                            ("PUSH_NOTIFICATION", "Mobile push notification"),
                            ("BRANDED", "App messaging"),
                        ],
                        help_text="Type of missive for which this template will be used",
                        max_length=20,
                        verbose_name="Missive Type",
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        help_text="Can contain variables: {{variable}}",
                        max_length=255,
                        verbose_name="Subject Template",
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        help_text="Can contain variables: {{variable}}",
                        verbose_name="Body Template",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to hide this template without deleting it",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Automatic creation date of the template",
                        verbose_name="Creation Date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Automatic last modification date",
                        verbose_name="Modification Date",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Missive Template",
                "verbose_name_plural": "Missive Templates",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["-created_at"], name="missive_mis_created_96fcd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["sender_email", "-created_at"],
                name="missive_mis_sender__4a2580_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["recipient_email", "-created_at"],
                name="missive_mis_recipie_a6b432_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["recipient_phone", "-created_at"],
                name="missive_mis_recipie_37a6a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["recipient_user", "-created_at"],
                name="missive_mis_recipie_7403a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["status", "-created_at"], name="missive_mis_status_533fe5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["missive_type", "status"], name="missive_mis_missive_29cd10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["external_id"], name="missive_mis_externa_9aa8a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["scheduled_at"], name="missive_mis_schedul_6cdc69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="missive_mis_content_3bbb20_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="missiveattachment",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="missive_mis_content_4ff039_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="missiveattachment",
            index=models.Index(
                fields=["missive", "order"], name="missive_mis_missive_b59af0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missiveattachment",
            index=models.Index(
                fields=["missive", "created_at"], name="missive_mis_missive_8f1c69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missiveevent",
            index=models.Index(
                fields=["missive", "-created_at"], name="missive_mis_missive_cac075_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missiveevent",
            index=models.Index(
                fields=["event_type"], name="missive_mis_event_t_398098_idx"
            ),
        ),
    ]
