# Generated by Django 5.2.8 on 2025-11-07 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Missive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "missive_type",
                    models.CharField(
                        choices=[
                            ("POSTAL", "Courrier postal"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("NOTIFICATION", "Notification in-app"),
                        ],
                        max_length=20,
                        verbose_name="Type de missive",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Basse"),
                            ("NORMAL", "Normale"),
                            ("HIGH", "Haute"),
                            ("URGENT", "Urgente"),
                        ],
                        default="NORMAL",
                        max_length=10,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Titre ou objet de la missive",
                        max_length=255,
                        verbose_name="Sujet",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Corps du message", verbose_name="Contenu"
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True,
                        help_text="Pour les emails",
                        max_length=254,
                        null=True,
                        verbose_name="Email destinataire",
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        blank=True,
                        help_text="Pour SMS/WhatsApp (format international +33...)",
                        max_length=20,
                        null=True,
                        verbose_name="Téléphone destinataire",
                    ),
                ),
                (
                    "recipient_address",
                    models.TextField(
                        blank=True,
                        help_text="Pour le courrier postal",
                        null=True,
                        verbose_name="Adresse postale",
                    ),
                ),
                (
                    "is_registered",
                    models.BooleanField(
                        default=False,
                        help_text="Email ou courrier recommandé avec accusé de réception",
                        verbose_name="Recommandé",
                    ),
                ),
                (
                    "requires_signature",
                    models.BooleanField(
                        default=False,
                        help_text="Pour courrier recommandé avec signature",
                        verbose_name="Signature requise",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En cours de traitement"),
                            ("SENT", "Envoyé"),
                            ("DELIVERED", "Délivré"),
                            ("READ", "Lu"),
                            ("FAILED", "Échec"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Laisser vide pour envoi immédiat",
                        null=True,
                        verbose_name="Date d'envoi programmée",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de réception"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de lecture"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de tracking du provider (LaPoste, SendGrid, etc.)",
                        max_length=255,
                        null=True,
                        verbose_name="ID externe",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Service utilisé pour l'envoi",
                        max_length=100,
                        null=True,
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Message d'erreur"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données additionnelles au format JSON",
                        verbose_name="Métadonnées",
                    ),
                ),
                (
                    "attachments_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de pièces jointes"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Coût d'envoi en euros",
                        max_digits=10,
                        null=True,
                        verbose_name="Coût",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_missives",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire (utilisateur)",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_missives",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Expéditeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Missive",
                "verbose_name_plural": "Missives",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MissiveAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="missive/attachments/%Y/%m/%d/",
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Nom du fichier"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="Taille (bytes)"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="Type MIME"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "missive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="missive.missive",
                        verbose_name="Missive",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce jointe",
                "verbose_name_plural": "Pièces jointes",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MissiveEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Ex: sent, delivered, opened, clicked, bounced, etc.",
                        max_length=50,
                        verbose_name="Type d'événement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En cours de traitement"),
                            ("SENT", "Envoyé"),
                            ("DELIVERED", "Délivré"),
                            ("READ", "Lu"),
                            ("FAILED", "Échec"),
                            ("CANCELLED", "Annulé"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Statut associé",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données additionnelles (IP, user agent, etc.)",
                        verbose_name="Métadonnées",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de l'événement"
                    ),
                ),
                (
                    "missive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="missive.missive",
                        verbose_name="Missive",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MissiveTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom du template"),
                ),
                (
                    "missive_type",
                    models.CharField(
                        choices=[
                            ("POSTAL", "Courrier postal"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("NOTIFICATION", "Notification in-app"),
                        ],
                        max_length=20,
                        verbose_name="Type de missive",
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        help_text="Peut contenir des variables : {{variable}}",
                        max_length=255,
                        verbose_name="Template du sujet",
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        help_text="Peut contenir des variables : {{variable}}",
                        verbose_name="Template du corps",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de missive",
                "verbose_name_plural": "Templates de missives",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["-created_at"], name="missive_mis_created_96fcd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["sender", "-created_at"], name="missive_mis_sender__a65902_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["recipient_user", "-created_at"],
                name="missive_mis_recipie_7403a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["status", "-created_at"], name="missive_mis_status_533fe5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["missive_type", "status"], name="missive_mis_missive_29cd10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["external_id"], name="missive_mis_externa_9aa8a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["scheduled_at"], name="missive_mis_schedul_6cdc69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missiveevent",
            index=models.Index(
                fields=["missive", "-created_at"], name="missive_mis_missive_cac075_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missiveevent",
            index=models.Index(
                fields=["event_type"], name="missive_mis_event_t_398098_idx"
            ),
        ),
    ]
