# Generated by Django 5.2.8 on 2025-11-07 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("missive", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="missive",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type du modèle qui génère cette missive (Order, Participant, Invoice, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="Type d'objet source",
            ),
        ),
        migrations.AddField(
            model_name="missive",
            name="object_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID de l'objet source",
                null=True,
                verbose_name="ID de l'objet source",
            ),
        ),
        migrations.AddField(
            model_name="missiveattachment",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description ou notes sur cette pièce jointe",
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="missiveattachment",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="URL du fichier hébergé en externe (S3, Google Drive, etc.)",
                max_length=500,
                null=True,
                verbose_name="URL externe",
            ),
        ),
        migrations.AlterField(
            model_name="missiveattachment",
            name="content_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Type MIME"
            ),
        ),
        migrations.AlterField(
            model_name="missiveattachment",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Laisser vide si le fichier est hébergé en externe",
                null=True,
                upload_to="missive/attachments/%Y/%m/%d/",
                verbose_name="Fichier local",
            ),
        ),
        migrations.AlterField(
            model_name="missiveattachment",
            name="file_size",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Taille (bytes)"
            ),
        ),
        migrations.AddIndex(
            model_name="missive",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="missive_mis_content_3bbb20_idx",
            ),
        ),
    ]
