# Generated by Django 5.2.8 on 2025-11-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missive", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="providerinfo",
            options={
                "default_permissions": (),
                "managed": False,
                "ordering": ["name"],
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
            },
        ),
        migrations.AddField(
            model_name="missive",
            name="provider_options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Options spécifiques au provider (ex: {'scheduled_time': 14, 'track_clicks': true, 'priority': 'high'})",
                verbose_name="Options du provider",
            ),
        ),
    ]
