# Generated by Django 5.2.8 on 2025-11-07 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("missive", "0002_missive_content_type_missive_object_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="missiveattachment",
            name="mime_type",
            field=models.CharField(
                blank=True,
                help_text="Type MIME du fichier (application/pdf, image/png, etc.)",
                max_length=100,
                verbose_name="Type MIME",
            ),
        ),
        migrations.AddField(
            model_name="missiveattachment",
            name="object_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID de l'objet auquel ce fichier est attaché",
                null=True,
                verbose_name="ID de l'objet",
            ),
        ),
        migrations.AlterField(
            model_name="missiveattachment",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type du modèle auquel ce fichier est attaché (Order, Invoice, etc.)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Type d'objet",
            ),
        ),
        migrations.AlterField(
            model_name="missiveattachment",
            name="missive",
            field=models.ForeignKey(
                blank=True,
                help_text="Missive à laquelle ce fichier est attaché",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="missive.missive",
                verbose_name="Missive",
            ),
        ),
        migrations.AddIndex(
            model_name="missiveattachment",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="missive_mis_content_4ff039_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="missiveattachment",
            index=models.Index(
                fields=["missive", "created_at"], name="missive_mis_missive_8f1c69_idx"
            ),
        ),
    ]
