# Generated by Django 5.2.8 on 2025-11-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missive", "0003_missiveattachment_mime_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="missive",
            name="preferred_provider",
            field=models.CharField(
                blank=True,
                help_text="Provider à utiliser pour l'envoi (sendgrid, twilio, laposte, etc.). Laissez vide pour utiliser la config par défaut.",
                max_length=50,
                null=True,
                verbose_name="Provider préféré",
            ),
        ),
        migrations.AlterField(
            model_name="missive",
            name="provider",
            field=models.CharField(
                blank=True,
                help_text="Provider réellement utilisé pour l'envoi (rempli automatiquement)",
                max_length=100,
                null=True,
                verbose_name="Provider utilisé",
            ),
        ),
    ]
