# Generated by Django 5.2.8 on 2025-11-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missive", "0004_missive_preferred_provider_alter_missive_provider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="missive",
            name="preferred_provider",
        ),
        migrations.AddField(
            model_name="missiveevent",
            name="provider",
            field=models.CharField(
                blank=True,
                help_text="Provider qui a généré cet événement",
                max_length=50,
                null=True,
                verbose_name="Provider",
            ),
        ),
        migrations.AlterField(
            model_name="missive",
            name="provider",
            field=models.CharField(
                blank=True,
                help_text="Provider à utiliser (sendgrid, twilio, laposte, etc.). Laissez vide pour utiliser la config par défaut.",
                max_length=50,
                null=True,
                verbose_name="Provider",
            ),
        ),
    ]
