# Generated by Django 5.2.8 on 2025-11-08 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("missive", "0005_remove_missive_preferred_provider_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="missive",
            name="recipient_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Optionnel si 'recipient' est fourni",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_missives",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Destinataire (utilisateur)",
            ),
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID de l'objet"
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Particulier"),
                            ("COMPANY", "Entreprise"),
                            ("ADMINISTRATION", "Administration"),
                        ],
                        default="INDIVIDUAL",
                        max_length=20,
                        verbose_name="Type de destinataire",
                    ),
                ),
                (
                    "civility",
                    models.CharField(
                        blank=True,
                        help_text="M., Mme, Dr, etc.",
                        max_length=10,
                        verbose_name="Civilité",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Prénom"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Nom"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Format international : +33600000000",
                        max_length=20,
                        null=True,
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        help_text="Format international",
                        max_length=20,
                        null=True,
                        verbose_name="Mobile",
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse ligne 1"
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse ligne 2"
                    ),
                ),
                (
                    "address_line3",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse ligne 3"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Code postal"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="État/Région"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="FR",
                        max_length=2,
                        verbose_name="Pays (code ISO)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Type d'objet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipient_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destinataire",
                "verbose_name_plural": "Destinataires",
                "ordering": ["last_name", "first_name", "company_name"],
            },
        ),
        migrations.AddField(
            model_name="missive",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                help_text="Destinataire avec toutes ses coordonnées",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="missives",
                to="missive.recipient",
                verbose_name="Destinataire",
            ),
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(fields=["email"], name="missive_rec_email_17df67_idx"),
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(fields=["phone"], name="missive_rec_phone_21d6b1_idx"),
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(fields=["mobile"], name="missive_rec_mobile_cf9247_idx"),
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="missive_rec_content_5122b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="missive_rec_last_na_322692_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recipient",
            index=models.Index(
                fields=["company_name"], name="missive_rec_company_ff7e0c_idx"
            ),
        ),
    ]
