# Generated by Django 5.2.8 on 2025-11-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missive", "0006_alter_missive_recipient_user_recipient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="missive",
            name="body_text",
            field=models.TextField(
                blank=True,
                help_text="Version texte brut du message (fallback pour emails, obligatoire pour SMS)",
                verbose_name="Contenu texte brut",
            ),
        ),
        migrations.AlterField(
            model_name="missive",
            name="body",
            field=models.TextField(
                help_text="Corps du message (HTML pour emails, texte pour SMS/WhatsApp)",
                verbose_name="Contenu HTML",
            ),
        ),
    ]
