# Generated by Django 5.2.8 on 2025-11-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("missive", "0007_missive_body_text_alter_missive_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="missiveattachment",
            options={
                "ordering": ["order", "created_at"],
                "verbose_name": "Pièce jointe",
                "verbose_name_plural": "Pièces jointes",
            },
        ),
        migrations.AddField(
            model_name="missiveattachment",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Ordre d'affichage (automatique si non fourni)",
                verbose_name="Ordre",
            ),
        ),
        migrations.AddIndex(
            model_name="missiveattachment",
            index=models.Index(
                fields=["missive", "order"], name="missive_mis_missive_b59af0_idx"
            ),
        ),
    ]
